apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkwarden

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - postgres.yaml
  - meilisearch.yaml
  - linkwarden.yaml
  # Uncomment to include ingress
  # - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: "latest"
